// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { console$Type } from "./console";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["console"]: console$Type;
    ["hardhat/console.sol:console"]: console$Type;
  }

  interface ContractTypesMap {
    ["console"]: GetContractReturnType<console$Type["abi"]>;
    ["hardhat/console.sol:console"]: GetContractReturnType<console$Type["abi"]>;
  }
}
