// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface console$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "console",
  "sourceName": "hardhat/console.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220adc3fd20212c0322e41a67c31a1624cfca859a4f2ab6b23ee6a7d4d9338b9c2764736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220adc3fd20212c0322e41a67c31a1624cfca859a4f2ab6b23ee6a7d4d9338b9c2764736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "console",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
  export function deployContract(
    contractName: "hardhat/console.sol:console",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "console",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<console$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "hardhat/console.sol:console",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<console$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "console",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
  export function getContractAt(
    contractName: "hardhat/console.sol:console",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
}
