// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Marketpulse$Type } from "./Marketpulse";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Marketpulse"]: Marketpulse$Type;
    ["contracts/Marketpulse.sol:Marketpulse"]: Marketpulse$Type;
  }

  interface ContractTypesMap {
    ["Marketpulse"]: GetContractReturnType<Marketpulse$Type["abi"]>;
    ["contracts/Marketpulse.sol:Marketpulse"]: GetContractReturnType<Marketpulse$Type["abi"]>;
  }
}
